import assert from 'node:assert/strict';
import test from 'node:test';
import {validateLifecycleGraph} from './lifecycle-graph.mjs';
import {isBerlinRelease} from './release-time.mjs';
const d=(c)=>`sha256:${c.repeat(64)}`;const node=(kind,id,parent,index)=>({id,kind,parent,edition:'2026-08-16',release:'2026-08-16T16:00:00+02:00[Europe/Berlin]',correlation:'edition-20260816',digest:d(kind==='staged'?'d':String(index)),ref:`state/edition/receipts/${id}.json`,owner:['released','staged'].includes(kind)?'pressman':'brass',status:{readiness:'ready',blocker:'blocked',finalization:'finalized',released:'released',staged:'staged'}[kind]});
const full=(blocked=false)=>{const ready=node('readiness','ready-one',null,1);const blocker=node('blocker','blocker-one',ready.id,2);const final=node('finalization','final-one',blocked?blocker.id:ready.id,3);const released=node('released','released-one',final.id,4);released.digest=d('d');const staged=node('staged','staged-one',released.id,5);return blocked?[ready,blocker,final,released,staged]:[ready,final,released,staged];};
test('accepts blocker-free, blocker-present, and explicit suffix graphs',()=>{const graph=full();assert.equal(validateLifecycleGraph(graph),true);assert.equal(validateLifecycleGraph(full(true)),true);assert.equal(validateLifecycleGraph(graph.slice(-2),{mode:'suffix',externalFinalization:graph[1]}),true);});
test('rejects complete hostile lifecycle matrix',()=>{const cases=[
  x=>{x[1].id=x[0].id;},x=>{x[1].ref=x[0].ref;},x=>{x[1].ref='state/edition/receipts//bad';},x=>{x[1].ref='state/edition/receipts/../bad';},x=>{x[1].ref='state/edition/receipts/./bad';},x=>{x[1].ref='state/edition/receipts/bad/';},x=>{x[1].edition='2026-08-17';},x=>{x[1].release='other';},x=>{x[1].correlation='other-correlation';},x=>{x[1].parent=null;},x=>{x[1].parent='orphan-id';},x=>{[x[0],x[1]]=[x[1],x[0]];},x=>{x[1].kind='staged';},x=>{x[1].owner='pressman';},x=>{x[1].status='released';},x=>{x.at(-1).digest=d('x');},x=>{x.shift();},x=>{x.splice(2,1);},x=>{x.splice(3,0,{...x[2],id:'final-two',ref:'state/edition/receipts/final-two.json'});},x=>{x.push({...x.at(-1),id:'staged-two',ref:'state/edition/receipts/staged-two.json'});}
];for(const mutate of cases){const value=structuredClone(full(true));mutate(value);assert.throws(()=>validateLifecycleGraph(value),/lifecycle graph/);}});
test('rejects sequence gaps, duplicates, nonintegers, and invalid suffix authority',()=>{for(const sequence of [[1,3,4,5],[1,2,2,3],[1,2.5,3,4]]){const value=full().map((item,index)=>({...item,sequence:sequence[index]}));assert.throws(()=>validateLifecycleGraph(value),/sequence/);}assert.throws(()=>validateLifecycleGraph(full().slice(-2),{mode:'suffix',externalFinalization:{...full()[1],id:'wrong-parent'}}),/suffix/);});
test('uses one lowercase safe receipt component language',()=>{for(const ref of ['state/edition/receipts/has space.json','state/edition/receipts/Upper.json','state/edition/receipts/back\\slash.json','state/edition/receipts/é.json','state/edition/receipts/../bad','state/edition/receipts//bad','state/edition/receipts/bad/','state/edition/receipts/./bad']){const value=full();value[1].ref=ref;assert.throws(()=>validateLifecycleGraph(value),/reference/);}});
test('suffix validates and reserves external finalization identity and reference',()=>{const graph=full(),suffix=graph.slice(-2),external=graph[1];for(const mutate of [value=>{value.owner='pressman';},value=>{value.status='released';},value=>{value.ref='state/edition/receipts/../bad';},value=>{value.release='bad';}]){const changed=structuredClone(external);mutate(changed);assert.throws(()=>validateLifecycleGraph(suffix,{mode:'suffix',externalFinalization:changed}),/suffix/);}const idCollision=structuredClone(suffix);idCollision[0].id=external.id;assert.throws(()=>validateLifecycleGraph(idCollision,{mode:'suffix',externalFinalization:external}),/unique/);const refCollision=structuredClone(suffix);refCollision[0].ref=external.ref;assert.throws(()=>validateLifecycleGraph(refCollision,{mode:'suffix',externalFinalization:external}),/unique/);});
test('sequence mode is decided once for the entire graph',()=>{const sequenced=full().map((item,index)=>({...item,sequence:index+1}));for(const index of [0,2]){const value=structuredClone(sequenced);delete value[index].sequence;assert.throws(()=>validateLifecycleGraph(value),/sequence presence/);}assert.equal(validateLifecycleGraph(full()),true);});
test('Berlin release validation is calendar-valid and DST-exact',()=>{assert.equal(isBerlinRelease('2026-08-16','2026-08-16T16:00:00+02:00[Europe/Berlin]'),true);assert.equal(isBerlinRelease('2026-01-16','2026-01-16T16:00:00+01:00[Europe/Berlin]'),true);for(const [edition,release] of [['2026-08-16','2026-08-16T16:00:00+01:00[Europe/Berlin]'],['2026-01-16','2026-01-16T16:00:00+02:00[Europe/Berlin]'],['2026-02-30','2026-02-30T16:00:00+01:00[Europe/Berlin]']])assert.equal(isBerlinRelease(edition,release),false);});
