import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, readdir, realpath, symlink, unlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { assembleEdition, checkpointLocalEdition, reconcileEdition, stageLocalRelease } from './newsroom.mjs';
import { validateLifecycle } from './validate-org.mjs';

const assignments=[{id:'a2',artifact_ref:'article/b',owner:'sprockett',status:'PASS'},{id:'a1',artifact_ref:'article/a',owner:'cogsworth',status:'PASS'}];
const artifacts=[{ref:'article/a',owner:'cogsworth',validated:true,digest:`sha256:${'a'.repeat(64)}`},{ref:'article/b',owner:'sprockett',validated:true,digest:`sha256:${'b'.repeat(64)}`}];
const releaseInput=async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'clank-release-'));const release='2026-08-16T16:00:00+02:00[Europe/Berlin]';const composition=assembleEdition(assignments,artifacts);const finalization={version:'v1',id:'final-20260816',kind:'finalization',edition:'2026-08-16',release,owner:'brass',correlation_id:'edition-20260816',causal_parent:'ready-20260816',artifact_digest:composition.digest,receipt_ref:'state/edition/receipts/finalization.json',status:'finalized'};const rawEditionStateRoot=path.join(root,'state','edition');await mkdir(path.join(rawEditionStateRoot,'receipts'),{recursive:true});const editionStateRoot=await realpath(rawEditionStateRoot);await writeFile(path.join(editionStateRoot,'receipts','finalization.json'),`${JSON.stringify(finalization)}\n`);return{composition,correlationId:'edition-20260816',edition:'2026-08-16',editionStateRoot,finalization,outputRoot:path.join(await realpath(root),'staging'),release};};

test('assembler enforces deterministic assignment/artifact bijection',()=>{const first=assembleEdition(assignments,artifacts);assert.deepEqual(first,assembleEdition([...assignments].reverse(),[...artifacts].reverse()));assert.throws(()=>assembleEdition(assignments,[artifacts[0],artifacts[0]]),/bijection/);assert.throws(()=>assembleEdition(assignments,[artifacts[0],{...artifacts[0],ref:'article/x'}]),/bijection/);assert.throws(()=>assembleEdition(assignments,[{...artifacts[0],validated:false},artifacts[1]]),/rejected/);});
test('release rejects tampered composition bytes',async()=>{const input=await releaseInput();input.composition.bytes+='tamper';await assert.rejects(stageLocalRelease(input),/digest mismatch/);});
test('release requires authentic finalization authority and matching identity and digest',async()=>{const input=await releaseInput();await assert.rejects(stageLocalRelease({...input,finalization:undefined}),/identity/);for(const mutate of [value=>{value.owner='pressman';},value=>{value.status='released';},value=>{value.receipt_ref='../forged';},value=>{value.edition='2026-08-17';},value=>{value.artifact_digest=`sha256:${'f'.repeat(64)}`;}]){const finalization=structuredClone(input.finalization);mutate(finalization);await assert.rejects(stageLocalRelease({...input,finalization}),/finalization|lifecycle graph/);}});
test('release authority comes from bounded canonical durable bytes',async()=>{const absent=await releaseInput();await unlink(path.join(absent.editionStateRoot,'receipts','finalization.json'));await assert.rejects(stageLocalRelease(absent),/unavailable/);const malformed=await releaseInput();await writeFile(path.join(malformed.editionStateRoot,'receipts','finalization.json'),'{');await assert.rejects(stageLocalRelease(malformed),/malformed/);const oversized=await releaseInput();await writeFile(path.join(oversized.editionStateRoot,'receipts','finalization.json'),'x'.repeat(65537));await assert.rejects(stageLocalRelease(oversized),/bounded|oversized/);const linked=await releaseInput();const linkedFile=path.join(linked.editionStateRoot,'receipts','finalization.json');await unlink(linkedFile);await symlink(path.join(linked.editionStateRoot,'elsewhere.json'),linkedFile);await assert.rejects(stageLocalRelease(linked),/unavailable/);const traversal=await releaseInput();traversal.finalization.receipt_ref='state/edition/receipts/../outside.json';await assert.rejects(stageLocalRelease(traversal),/shape|path/);});
test('receipt roots and components cannot redirect durable authority',async()=>{const rootLink=await releaseInput();const actual=rootLink.editionStateRoot;const alias=`${actual}-alias`;await symlink(actual,alias);await assert.rejects(stageLocalRelease({...rootLink,editionStateRoot:alias}),/real directories|canonical/);const intermediate=await releaseInput();intermediate.finalization.receipt_ref='state/edition/receipts/nested/finalization.json';await assert.rejects(stageLocalRelease(intermediate),/path/);const finalLink=await releaseInput();const file=path.join(finalLink.editionStateRoot,'receipts','finalization.json');await unlink(file);await writeFile(path.join(finalLink.editionStateRoot,'target.json'),JSON.stringify(finalLink.finalization));await symlink(path.join(finalLink.editionStateRoot,'target.json'),file);await assert.rejects(stageLocalRelease(finalLink),/unavailable/);});
test('replacement after open cannot change the receipt bytes being validated',async()=>{const input=await releaseInput();const file=path.join(input.editionStateRoot,'receipts','finalization.json');const result=await stageLocalRelease({...input,afterReceiptOpen:async()=>{await unlink(file);await writeFile(file,'{\"forged\":true}\n');}});assert.equal(result.released.causal_parent,input.finalization.id);});
test('concurrent release and retries converge to one artifact and durable schema-valid receipts',async()=>{const input=await releaseInput();const results=await Promise.all(Array.from({length:8},()=>stageLocalRelease(input)));assert.ok(results.every((item)=>JSON.stringify(item)===JSON.stringify(results[0])));assert.equal((await readdir(input.outputRoot)).length,1);assert.deepEqual((await readdir(path.join(input.editionStateRoot,'receipts'))).sort(),['finalization.json',path.basename(results[0].staged.receipt_ref),path.basename(results[0].released.receipt_ref)].sort());validateLifecycle([results[0].released,results[0].staged],{mode:'suffix',externalFinalization:input.finalization});});
test('post-artifact crash and stale temp retry converge without conflict',async()=>{const input=await releaseInput();await assert.rejects(stageLocalRelease({...input,afterArtifact:async()=>{throw new Error('crash');}}),/crash/);await writeFile(path.join(input.outputRoot,`${path.basename((await readdir(input.outputRoot))[0])}.tmp-stale`),'stale');const result=await stageLocalRelease(input);assert.equal(await readFile(result.artifact,'utf8').then((bytes)=>bytes.includes(input.composition.digest)),true);validateLifecycle([result.released,result.staged],{mode:'suffix',externalFinalization:input.finalization});});
test('crash after durable released receipt resumes staged receipt atomically',async()=>{const input=await releaseInput();await assert.rejects(stageLocalRelease({...input,afterReleased:async()=>{throw new Error('receipt crash');}}),/receipt crash/);assert.equal((await readdir(path.join(input.editionStateRoot,'receipts'))).length,2);const result=await stageLocalRelease(input);assert.equal((await readdir(path.join(input.editionStateRoot,'receipts'))).length,3);validateLifecycle([result.released,result.staged],{mode:'suffix',externalFinalization:input.finalization});});

const record=(sequence,state,id,parent)=>({source:'state/edition',sequence,state,id,causal_parent:parent,edition:'2026-08-16',release:'2026-08-16T16:00:00+02:00[Europe/Berlin]',correlation_id:'edition-20260816',artifact_digest:`sha256:${String(sequence).repeat(64)}`,receipt_ref:`state/edition/receipts/${id}.json`});
const history=()=>{const items=[record(1,'drafting','draft-20260816',null),record(2,'finalized','final-20260816','draft-20260816'),record(3,'released','released-20260816','final-20260816'),record(4,'staged','staged-20260816','released-20260816')];items[3].artifact_digest=items[2].artifact_digest;return items;};
test('reconciliation validates durable schema, identity, contiguous sequence, transitions and parents',()=>{assert.equal(reconcileEdition(history()),'staged');for(const mutate of [items=>{items[2].sequence=4;},items=>items.push({...items[1],id:'other-final'}),items=>{items[2].correlation_id='forged-correlation';},items=>{items[2].causal_parent='draft-20260816';},items=>{items[1].state='staged';}]){const items=history();mutate(items);assert.throws(()=>reconcileEdition(items),/lifecycle graph|shape/);}});
test('reconciliation shape adapter rejects extra and missing fields',()=>{const extra=history();extra[0].unexpected=true;assert.throws(()=>reconcileEdition(extra),/shape/);const missing=history();delete missing[0].receipt_ref;assert.throws(()=>reconcileEdition(missing),/shape/);});
test('reconciliation accepts only arrays and requires sequence on every nonempty record',()=>{assert.equal(reconcileEdition([]),'empty');assert.throws(()=>reconcileEdition(null),/array/);assert.throws(()=>reconcileEdition({}),/array/);const missing=history();delete missing[1].sequence;assert.throws(()=>reconcileEdition(missing),/shape|sequence/);});
test('checkpoint cognition converges retries through graph, assembler and release modules',async()=>{const root=await realpath(await mkdtemp(path.join(os.tmpdir(),'clank-checkpoint-'))),state=path.join(root,'state'),output=path.join(root,'staging'),base={edition:'2026-08-16',release:'2026-08-16T16:00:00+02:00[Europe/Berlin]',correlationId:'broker-checkpoint-test',editionStateRoot:state,outputRoot:output,evidenceDigest:`sha256:${'a'.repeat(64)}`};await Promise.all([checkpointLocalEdition({...base,phase:'drafting'}),checkpointLocalEdition({...base,phase:'drafting'})]);await checkpointLocalEdition({...base,phase:'finalization',assignments:[{id:'one',artifact_ref:'article/one',owner:'cogsworth',status:'PASS'}],artifacts:[{ref:'article/one',owner:'cogsworth',validated:true,digest:`sha256:${'b'.repeat(64)}`}]});const releases=await Promise.all([checkpointLocalEdition({...base,phase:'release'}),checkpointLocalEdition({...base,phase:'release'})]);assert.deepEqual(releases[0],releases[1]);assert.deepEqual((await readdir(path.join(state,'records'))).sort(),['001-drafting.json','002-finalized.json','003-released.json','004-staged.json']);});
