import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmod, mkdir, mkdtemp, readFile, readdir, realpath, rm, writeFile } from 'node:fs/promises';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import test from 'node:test';
import { importBrowserBrokerResult } from '../scripts/browser-broker-import.mjs';
import { assertProvenance } from './provenance.mjs';

const load=async file=>JSON.parse(await readFile(file,'utf8'));const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));const compiled=(...parts)=>path.join(process.env.CLANK_E2E_COMPILED_ROOT,...parts);const sha=value=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
class Runtime{constructor(child){this.child=child;this.waiters=[];this.values=[];let buffer='';child.stdout.setEncoding('utf8');child.stdout.on('data',chunk=>{buffer+=chunk;for(let end;(end=buffer.indexOf('\n'))>=0;){const line=buffer.slice(0,end);buffer=buffer.slice(end+1);if(line){const value=JSON.parse(line),waiter=this.waiters.shift();waiter?waiter(value):this.values.push(value);}}});}request(value){this.child.stdin.write(`${JSON.stringify(value)}\n`);return this.values.length?Promise.resolve(this.values.shift()):new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('runtime timeout')),10000);this.waiters.push(result=>{clearTimeout(timer);resolve(result);});});}async stop(){if(this.child.exitCode!==null)return;await this.request({type:'stop'});this.child.stdin.end();await new Promise(resolve=>this.child.once('exit',resolve));}}
const scheduleDelivery=(config,hour)=>{const agent=config.agents.find(item=>item.id==='agent:brass'),source=agent.schedule,schedule={kind:source.kind,cron:source.cron,timezone:source.timezone,prompt:source.prompt},identity=createHash('sha256').update(JSON.stringify({agentId:agent.id,schedule})).digest('hex');return`schedule:${identity}:2026-08-16T${hour}:00@GMT+02:00`;};
async function startRuntime(config,root,now,promotion,clientConfig){const image=process.env.CLANK_E2E_DAIMON_IMAGE,linuxMoltnet=process.env.CLANK_E2E_MOLTNET_LINUX_BIN,e2eRoot=process.env.CLANK_E2E_ROOT;assert.ok(image&&linuxMoltnet&&e2eRoot);const hostRuntimePort=await port(),containerRuntimePort=await port();const prompt=config.agents.find(agent=>agent.id==='agent:brass').schedule.prompt,releaseText='@pressman execute the validated local release handoff.',common={edition:'2026-08-16',release:'2026-08-16T16:00:00+02:00[Europe/Berlin]',correlationId:promotion.correlation_id,editionStateRoot:'/state/edition-state',outputRoot:'/state/staging',evidenceDigest:promotion.evidence_digest},trigger=(agent_id,wake_kind,text,delivery_id)=>({agent_id,wake_kind,text_sha256:createHash('sha256').update(text).digest('hex'),...(delivery_id?{delivery_id}:{})});const cognition_actions=[{delivery_id:`moltnet:${promotion.occurrence_id}`,network_id:'clank-newsroom',target:'room:sensor',text:`${promotion.selected_desks.map(desk=>`@${desk}`).join(' ')} qualified browser-broker promotion; begin assigned grounding.`},{type:'mcp_call',trigger:trigger('agent:brass','schedule',prompt,scheduleDelivery(config,'14')),server_id:'newsroom-brass',tool:'checkpoint',arguments:{...common,phase:'drafting'}},{type:'mcp_call',trigger:trigger('agent:brass','schedule',prompt,scheduleDelivery(config,'15')),server_id:'newsroom-brass',tool:'checkpoint',arguments:{...common,phase:'finalization',assignments:[{id:'one',artifact_ref:'article/one',owner:'cogsworth',status:'PASS'}],artifacts:[{ref:'article/one',owner:'cogsworth',validated:true,digest:sha('filing')}]}},{delivery_id:scheduleDelivery(config,'16'),network_id:'clank-newsroom',target:'room:assignment',text:releaseText},{type:'mcp_call',trigger:trigger('agent:pressman','message',`[room assignment] klaxon\n${releaseText}`),server_id:'newsroom-pressman',tool:'checkpoint',arguments:{...common,phase:'release'}}];const child=spawn('docker',['run','--rm','-i','--platform','linux/amd64','--user',`${process.getuid()}:${process.getgid()}`,'-p',`127.0.0.1:${hostRuntimePort}:${containerRuntimePort}`,'-e','DAIMON_EXPLICIT_TEST_RUNTIME=1','-e','CLANK_MOLTNET_KLAXON_TOKEN=e2e-klaxon-token','-v',`${e2eRoot}:/e2e:ro`,'-v',`${root}:/state`,'-v',`${linuxMoltnet}:/opt/moltnet:ro`,image],{stdio:['pipe','pipe','pipe']});const runtime=new Runtime(child),started=await runtime.request({type:'start',acceptance_store_path:'/state/acceptance',config,control_token:'clank-e2e-control',now_ms:now,http_host:'0.0.0.0',http_port:containerRuntimePort,moltnet_cli_path:'/opt/moltnet',moltnet_client_config_path:`/state/${path.basename(clientConfig)}`,mcp_config_path:'/e2e/mcp/explicit-test-mcp.json',mcp_receipt_path:'/e2e/mcp/explicit-test-mcp-receipt.json',cognition_actions});assert.equal(started.type,'started',JSON.stringify(started));return{runtime,baseUrl:`http://127.0.0.1:${hostRuntimePort}`,container:child};}
const port=()=>new Promise((resolve,reject)=>{const server=net.createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const value=server.address().port;server.close(error=>error?reject(error):resolve(value));});});
async function healthy(url){for(let i=0;i<100;i++){try{if((await fetch(url)).ok)return;}catch{}await sleep(25);}throw new Error('Moltnet health timeout');}
async function stop(child){if(!child||child.exitCode!==null)return;child.kill('SIGTERM');await Promise.race([new Promise(resolve=>child.once('exit',resolve)),sleep(5000).then(()=>child.kill('SIGKILL'))]);}
async function moltnet(root,runtimeUrl,baseUrl){const binary=process.env.CLANK_E2E_MOLTNET_BIN;
assert.ok(binary);
const serverConfig=await load(compiled('container','rootfs','var','lib','spawnfile','moltnet','servers','clank-and-slop-clank-newsroom','Moltnet.json'));
serverConfig.server.listen_addr=new URL(baseUrl).host;
serverConfig.storage={kind:'sqlite',sqlite:{path:path.join(root,'moltnet.sqlite')}};
for(const token of serverConfig.auth.tokens)token.value=`e2e-${token.id}-token`;
const serverFile=path.join(root,'Moltnet.json');
await writeFile(serverFile,JSON.stringify(serverConfig));
await chmod(serverFile,0o600);
const server=spawn(binary,['start','--config',serverFile],{stdio:'ignore'});
await healthy(`${baseUrl}/healthz`);
const nodes=[];
for(const agent of ['klaxon','cogsworth','vesta','pressman']){const nodeConfig=await load(compiled('container','rootfs','var','lib','spawnfile','moltnet','nodes',`clank-and-slop-clank-newsroom-${agent}.json`));
nodeConfig.moltnet.base_url=baseUrl;
nodeConfig.attachments[0].runtime.control_url=runtimeUrl;
nodeConfig.attachments[0].runtime.receipt_store_path=path.join(root,`${agent}-delivery.json`);
const nodeFile=path.join(root,`MoltnetNode-${agent}.json`);
await writeFile(nodeFile,JSON.stringify(nodeConfig));
await chmod(nodeFile,0o600);
nodes.push(spawn(binary,['node',nodeFile],{env:{...process.env,[`CLANK_MOLTNET_${agent.toUpperCase()}_TOKEN`]:`e2e-${agent}-token`,SPAWNFILE_DAIMON_CONTROL_TOKEN:'clank-e2e-control'},stdio:'ignore'}));
}for(let attempt=0;attempt<1200;attempt++){const response=await fetch(`${baseUrl}/v1/agents?limit=100`,{headers:{authorization:'Bearer e2e-operator-token'}});if(response.ok){const page=await response.json();if(['klaxon','cogsworth','vesta','pressman'].every(id=>page.agents?.some(agent=>agent.id===id&&agent.connected)))break;}if(attempt===1199)throw new Error('Moltnet nodes did not become ready');await sleep(25);}
return{nodes,server,async send(sensor){const body={id:sensor.id,target:{kind:'dm',dm_id:'dm-research-sensor-klaxon',participant_ids:['klaxon','research-sensor']},from:{type:'agent',id:'research-sensor',network_id:'clank-newsroom'},parts:[{kind:'text',text:sensor.text}]};
const response=await fetch(`${baseUrl}/v1/messages`,{method:'POST',headers:{authorization:'Bearer e2e-research-sensor-token','content-type':'application/json'},body:JSON.stringify(body)});
assert.equal(response.status,202,await response.text());
}};
}
async function wake(runtime,...agents){for(let i=0;i<100;i++){const value=await runtime.request({type:'snapshot'});if(!Array.isArray(value.wakes))throw new Error(JSON.stringify(value));if(agents.every(agent=>value.wakes.some(item=>item.agent_id===agent)))return value;await sleep(25);}throw new Error(`missing ${agents.join(', ')} wake`);}
test('compiled sensor transport, native schedule, restart, and local release are durable',async t=>{for(const name of ['CLANK_E2E_COMPILED_ROOT','CLANK_E2E_DAIMON_IMAGE','CLANK_E2E_MOLTNET_BIN','CLANK_E2E_MOLTNET_LINUX_BIN','CLANK_E2E_PROVENANCE'])assert.ok(process.env[name],`${name} required`);
const root=await realpath(await mkdtemp(path.join(process.env.CLANK_E2E_ROOT,'state-')));
t.after(()=>rm(root,{recursive:true,force:true}));
const report=await load(compiled('spawnfile-report.json'));
const provenance=assertProvenance(await load(process.env.CLANK_E2E_PROVENANCE));
assert.equal(provenance.compile_fingerprint,report.compile_fingerprint);
assert.equal(provenance.image_manifest_digest,process.env.CLANK_E2E_DAIMON_IMAGE.split('@')[1]);
assert.match(report.compile_fingerprint,/^sf1:[a-f0-9]{12}$/);
assert.ok(Date.now()-Date.parse(report.generated_at)<600000);
const config=await load(compiled('container','rootfs','var','lib','spawnfile','instances','daimon','daimon-organization','daimon','daimon-organization-runtime.json'));
const brass=config.agents.find(agent=>agent.id==='agent:brass');
assert.equal(brass.schedule.cron,'0 14,15,16 * * *');
assert.equal(brass.schedule.timezone,'Europe/Berlin');
const pressman=(await readFile(compiled('entrypoint.sh'),'utf8')).split('\n').find(line=>line.includes("prepare_volume_resource 'public-content'")&&line.includes('/agents/pressman/staging'));
assert.match(pressman,/clank-release-staging/);
assert.doesNotMatch(pressman,/github|https?:\/\/|credential|token|prepare_git_resource/i);
const entrypoint=await readFile(compiled('entrypoint.sh'),'utf8');
const editionMounts=entrypoint.split('\n').filter(line=>line.startsWith("prepare_volume_resource 'edition-state'"));
assert.equal(editionMounts.length,config.agents.length);
const editionBackings=new Set(editionMounts.map(line=>line.match(/'([^']*clank-edition-state-[^']*)' 'mutable'/)?.[1]));
assert.equal(editionBackings.size,1);assert.ok(!editionBackings.has(undefined));
const compiledServer=await load(compiled('container','rootfs','var','lib','spawnfile','moltnet','servers','clank-and-slop-clank-newsroom','Moltnet.json'));
assert.equal(compiledServer.network.id,'clank-newsroom');
assert.equal(compiledServer.storage.kind,'sqlite');
assert.equal(compiledServer.storage.sqlite.path,'/var/lib/spawnfile/moltnet/networks/clank-newsroom/moltnet.sqlite');
const store=path.join(root,'acceptance');
await mkdir(store,{mode:0o700});
await chmod(store,0o700);
const state=path.join(root,'edition-state'),receipts=path.join(state,'receipts');
await mkdir(receipts,{recursive:true});
const promoted=await importBrowserBrokerResult({edition:'2026-08-16',release:'2026-08-16T16:00:00+02:00[Europe/Berlin]',result:await load(path.join(import.meta.dirname,'fixtures','promoted-broker.json')),selectedDesks:['cogsworth','vesta'],stateRoot:state});
const baseUrl=`http://127.0.0.1:${await port()}`;
const clientConfig=await load(compiled('runtimes','daimon','agents','klaxon','workspace','.moltnet','config.json'));
clientConfig.attachments[0].base_url=`http://host.docker.internal:${new URL(baseUrl).port}`;
const clientConfigPath=path.join(root,'klaxon-client.json');
await writeFile(clientConfigPath,JSON.stringify(clientConfig));
let active,transport;
try{active=await startRuntime(config,root,Date.parse('2026-08-16T13:59:00+02:00'),promoted.record,clientConfigPath);
transport=await moltnet(root,active.baseUrl,baseUrl);
await transport.send(promoted.sensor);
const routed=await wake(active.runtime,'agent:cogsworth','agent:vesta');
assert.ok(routed.wakes.some(item=>item.agent_id==='agent:cogsworth'));
assert.equal(routed.action_receipts.filter(item=>item.delivery_id===`moltnet:${promoted.sensor.id}`).length,1);
const draft=await active.runtime.request({type:'advance',now_ms:Date.parse('2026-08-16T14:00:00+02:00')});
assert.equal(draft.wakes.filter(item=>item.agent_id==='agent:brass').length,1);
assert.ok(draft.action_receipts.some(item=>item.type==='mcp_call'&&item.server_id==='newsroom-brass'&&!item.is_error),JSON.stringify(draft.action_receipts));
await active.runtime.stop();
await Promise.all(transport.nodes.map(stop));
await stop(transport.server);transport=undefined;
active=await startRuntime(config,root,Date.parse('2026-08-16T14:01:00+02:00'),promoted.record,clientConfigPath);
transport=await moltnet(root,active.baseUrl,baseUrl);
await transport.send(promoted.sensor);
const finalWake=await active.runtime.request({type:'advance',now_ms:Date.parse('2026-08-16T15:00:00+02:00')});
assert.equal(finalWake.wakes.filter(item=>item.agent_id==='agent:brass').length,1);
assert.equal(finalWake.wakes.some(item=>item.agent_id==='agent:klaxon'),false);
assert.ok(finalWake.action_receipts.some(item=>item.type==='mcp_call'&&item.server_id==='newsroom-brass'&&!item.is_error));
await active.runtime.stop();
await Promise.all(transport.nodes.map(stop));
await stop(transport.server);transport=undefined;
active=await startRuntime(config,root,Date.parse('2026-08-16T15:01:00+02:00'),promoted.record,clientConfigPath);
transport=await moltnet(root,active.baseUrl,baseUrl);
const releaseWake=await active.runtime.request({type:'advance',now_ms:Date.parse('2026-08-16T16:00:00+02:00')});
assert.equal(releaseWake.wakes.filter(item=>item.agent_id==='agent:brass').length,1);
await wake(active.runtime,'agent:pressman');
const released=await active.runtime.request({type:'snapshot'});
assert.ok(released.action_receipts.some(item=>item.type==='mcp_call'&&item.server_id==='newsroom-pressman'&&!item.is_error),JSON.stringify({action_receipts:released.action_receipts,wakes:released.wakes}));
assert.equal((await readdir(path.join(root,'staging'))).length,1);
assert.equal((await readdir(receipts)).filter(name=>name.includes('.staged.')).length,1);
}finally{await active?.runtime.stop().catch(()=>{});
await Promise.all((transport?.nodes??[]).map(stop));
await stop(transport?.server);
}});
